name: Type checks

on:
  - push
  - pull_request

jobs:
  mypy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: uv sync
      - name: Python linter
        run: uv run mypy --config-file pyproject.toml .
