name: Pyright

on:
  - push
  - pull_request

jobs:
  pyright:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    name: "Pyright"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run Pyright tests
        run: uv run pyright .
