name: Unit Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'
      - name: Run unit tests
        run: uv run --group test pytest --cov=service_client --cov=server --cov-report term-missing
